#!/usr/bin/env bash
# penguinRice

# Start sxhkd
killall -q sxhkd 
sleep 0.2
sxhkd -c ~/.config/bspwm/config/bspwm/keys &

# Audio
pipewire &

# Config files
~/.screenlayout/monitor.sh
~/.config/bspwm/config/bspwm/cfg
~/.config/bspwm/config/bspwm/decoration
~/.config/bspwm/config/bspwm/autostart
~/.config/bspwm/config/bspwm/misc
